apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-eureka
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.serviceName }} {{ .Values.eazybankcommon.service.port }}; do sleep 5; done']
      restartPolicy: Never