apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-eureka-cha
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed #before-hookcreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wait-for-eureka-cha
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.global.eurekaServiceName }} {{ .Values.global.eurekaServicePort }}; do sleep 5; done']
# spec:
#   restartPolicy: Never
#   containers:
#     - name: wait-for-eureka-cha
#       image: busybox
#       command: ['sh', '-c', 'until nc -z {{ .Values.global.eurekaServiceName }} {{ .Values.global.eurekaServicePort }}; do sleep 5; done']
      
  # template:
  #   spec:
  #     containers:
  #       - name: wait-for-eureka
  #         image: busybox
  #         command: ['sh', '-c', 'until nc -z team6-eureka-cha-sv 80; do sleep 5; done']