apiVersion: v1 #batch/v1
kind: Pod  #Job
metadata:
  name: wait-for-eureka-cha
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hookcreation
spec:
  restartPolicy: Never
  containers:
    - name: wait-for-eureka-cha
      image: busybox
      # command: ['sh', '-c', 'until nc -z team6-eureka-cha-sv 80; do sleep 5; done']
      command: ['sh', '-c', 'until nc -z {{ .Values.global.eurekaServiceName }} {{ .Values.global.eurekaServicePort }}; do sleep 5; done']
      
  # template:
  #   spec:
  #     containers:
  #       - name: wait-for-eureka
  #         image: busybox
  #         command: ['sh', '-c', 'until nc -z team6-eureka-cha-sv 80; do sleep 5; done']