apiVersion: batch/v1
kind: Pod  #Job
metadata:
  name: wait-for-eureka
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hookcreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z team6-eureka-cha-sv 80; do sleep 5; done']