apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-eureka
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.eurekaserver.serviceName }} {{ .Values.eurekaserver.service.port }}; do sleep 5; done']
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-configserver
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: wait-for-configserver
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.configserver.serviceName }} {{ .Values.configserver.service.port }}; do sleep 5; done']
          restartPolicy: Never

---

# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: wait-for-accounts
#   annotations:
#     "helm.sh/hook": post-install,post-upgrade
#     "helm.sh/hook-weight": "2"
#     "helm.sh/hook-delete-policy": before-hook-creation
# spec:
#   template:
#     spec:
#       containers:
#         - name: wait-for-accounts
#           image: busybox
#           command: ['sh', '-c', 'until nc -z {{ .Values.accounts.serviceName }} {{ .Values.accounts.service.port }}; do sleep 5; done']
#       restartPolicy: Never
